### ISSUE TITLE
How to use it without <UserAgent>?

### ISSUE THREAD

**Issue by vendramini** [quentin-sommer/react-useragent#23]
Good evening.

Is there some 'isMobile' variable available? I searched in source code but found nothing.
Sometimes we need to add className depending if isMobile or not; or do some logical before `render`; others I use `<UserAgent>`.

Nice work, thank you =)

**Comment by quentin-sommer** [comment]
Hi,

There isn't any way to access the results without the `<UserAgent/>` component but I think you can achieve what you want using the function as a child api:

```jsx
function MyComponent() {
  return (
    <UserAgent mobile>
      {uaIsMobile => {
        let className = 'not-mobile'

        if (uaIsMobile) {
          // custom class
          className = 'mobile'
          // custom processing
          data = doProcessing()

          return <MobileComponent className={className} data={data} />
        }

        return <DesktopComponent className={className} />
      }}
    </UserAgent>
  )
}
```

You can see this pattern in the [readme](https://github.com/quentin-sommer/react-useragent)

Cheers!

**Comment by vendramini** [comment]
Got it. Thank you!

And is there some way to check inside `useEffect(() => {//here}, []);`?

**Comment by quentin-sommer** [comment]
Unfortunately no, there isn't any hook api for the library. Happy to review a PR if you want to make one!

**Comment by quentin-sommer** [comment]
I'll go ahead and close this issue. Feel free to open a new one if you need.
