### ISSUE TITLE
Bump React version

### ISSUE THREAD

**Issue by mmbrtstd** [quentin-sommer/react-useragent#342]
The project is already using the types/react v17. Is it possible to bump the react version too to 17 and update the peer dependency? I'm getting an error installing on a react 17 project.

**Comment by quentin-sommer** [comment]
No problem 👍

**Comment by quentin-sommer** [comment]
Fixed in [3.1.1](https://github.com/quentin-sommer/react-useragent/releases/tag/v3.1.1)
