### ISSUE TITLE
Bump React version

### ISSUE THREAD

**Issue by samallisonds** [quentin-sommer/react-useragent#376]
I'm getting an error installing on a react 18 project. Is it possible update this project to support installing in a react 18 project please?

**Comment by quentin-sommer** [comment]
Sure 👍 Fixed in `3.2.0`

**Comment by samallisonds** [comment]
Thank you! Any idea when that version will appear on npm?

**Comment by samallisonds** [comment]
It is there now - thanks again!

**Comment by quentin-sommer** [comment]
no problem!
