### ISSUE TITLE
Build errors on Next.js 13 and above

### ISSUE THREAD

**Issue by ghost** [quentin-sommer/react-useragent#409]
With major changes to React 18 and a heavy reliance on React Server Components on Next.js 13, it causes the build to fail even with `"use client";` directive, specifically throwing a [prerender error](https://nextjs.org/docs/messages/prerender-error)

![Screenshot 2023-09-28 122333](https://github.com/quentin-sommer/react-useragent/assets/94678583/b7c0c2aa-d05e-41b4-a1ed-4eb9f1992a2b)

Another solution I've tried to use `next/dynamic` with `dynamic(() => import("@quentin-sommer/react-useragent").then((c) => c.UserAgentProvider), { ssr: false })` but to no avail, still give me the same previous error

**Comment by quentin-sommer** [comment]
Hey, thanks for reporting! Could you share a basic next.js 13 setup showing the error?

**Comment by ghost** [comment]
Sure thing! Here's a minimal [CodeSandbox demo](https://codesandbox.io/p/sandbox/nextjs-ua-demo-9xwwdj?file=%2Fapp%2FUAClientProvider.tsx%3A6%2C25) of it

One thing worth mentioning is while I was setting this up, the browser flashed temporarily and gave me the `ReferenceError: window is not defined` error in the console every time I made changes on dev mode; but it didn't give me the error window on the browser, it just flashed like it didn't happen. Probably a weird thing with server components, perhaps?

**Comment by quentin-sommer** [comment]
Thanks! I'll take a look

**Comment by quentin-sommer** [comment]
Here's a working example: https://codesandbox.io/p/sandbox/nextjs-ua-demo-9xwwdj?file=%2Fapp%2FUAClientProvider.tsx%3A6%2C25
`layout.tsx` uses `import { headers } from 'next/headers'` to get headers and user agent. it is a server side component.
it renders `<UAClientProvider ua={headers().get('user-agent')}>{children}</UAClientProvider>` which is a client side component. The lib needs context so it has to be client component.

then `UAClientProvider` renders `<UserAgentProvider ua={ua}>` and contains additional bit of logic to retrieve ua from the window object to handle cases where the component is not rendered by a server component initially.

Cheers

**Comment by ghost** [comment]
Ooh, such an interesting approach! However, it seems like you've linked the same CodeSandbox demo too since they have the same link as my initial demo; I've tried recreating the sandbox that I created weeks ago from your suggestions but I wasn't able to reproduce it sadly.

on top of that, I'm getting errors from the browser console when passing `children` props from `<UAProvider>`: `Invalid prop `children` of type `array` supplied to `UAProvider`, expected a single ReactElement.` It's unrelated to the issue at hand but it's worth noting at least lol

**Comment by quentin-sommer** [comment]
Right sorry about the link here is the link to my fork of your sandbox: https://codesandbox.io/p/sandbox/nextjs-ua-demo-forked-fk8ldv

**Comment by ghost** [comment]
That's more like it - thanks for the help!

**Comment by quentin-sommer** [comment]
No problem!
