### ISSUE TITLE
Wrong prop name on README

### ISSUE THREAD

**Issue by fhosen** [quentin-sommer/react-useragent#68]
Hello!

I think I've spotted a small issue.

The readme states that in order to get the parser one should pass the property `returnFullParser` to the component `UserAgent`, but instead it works only with `returnfullParser `.

**Comment by quentin-sommer** [comment]
Hi,

This was a typo bug present until v2.0.0 ([changelog](https://github.com/quentin-sommer/react-useragent/blob/0aa2fd04e4041a62524f4e0a6bf07b671cca0429/CHANGELOG.md#v200-2018-10-14)), I think you might have an old version of the library.
You should update to `^3.1.0`. Then `returnFullParser` will work and `returnfullParser` will stop working!

**Comment by fhosen** [comment]
Oh my bad! Thanks for the quick response :)
